### ISSUE TITLE
Support for custom option names

### ISSUE THREAD

**Issue by regadas** [alexarchambault/case-app#181]
Hi @alexarchambault!

I'm just wondering if adding support for other types of option names (i.e camel case `--camelCase`) is this something that could be added to `case-app` or if you want to keep it opinionated and only support `--camel-case`.

**Comment by alexarchambault** [comment]
Hi @regadas,

You mean to [convert field names to option names](https://github.com/alexarchambault/case-app/blob/6668d3f19c7af9ae41751c2d89792cdf7e89d7a4/README.md#pascal-case-conversion)?

Camel case is fine, the doc should actually say camel case rather than pascal case. It's fine with both camel case (like `camelCase`, which gives `--camel-case` as an option) and pascal case (like `PascalCase`, giving `--pascal-case`).

It could accept other cases automatically, like serpent case (`serpent_case`), if they don't conflict with the current handling of pascal / camel case.

**Comment by regadas** [comment]
Sorry @alexarchambault ! I wasn't totally clear :) what i meant with:
>  support for other types of case's (i.e camel case)

was actually adding support for `--camelCase` as well.

(I'll update the description of this issue)

**Comment by alexarchambault** [comment]
Oh, I see.

Currently, the logic handling the camel case to serpent case is quite ingrained, via [this call](https://github.com/alexarchambault/case-app/blob/f5bc38eb6b84af62aa861691ee6229a0c13fff40/core/shared/src/main/scala/caseapp/core/util/NameOps.scala#L12-L13) in particular. It might be possible to allow to configure that (via extra fields in [`Parser`](https://github.com/alexarchambault/case-app/blob/6668d3f19c7af9ae41751c2d89792cdf7e89d7a4/core/shared/src/main/scala/caseapp/core/parser/Parser.scala) and [`Help`](https://github.com/alexarchambault/case-app/blob/6668d3f19c7af9ae41751c2d89792cdf7e89d7a4/core/shared/src/main/scala/caseapp/core/help/Help.scala) say), and then passing these around so that they are passed to [`NameOps.option`](https://github.com/alexarchambault/case-app/blob/f5bc38eb6b84af62aa861691ee6229a0c13fff40/core/shared/src/main/scala/caseapp/core/util/NameOps.scala#L17), but I'm not sure it's straightforward to do.

**Comment by regadas** [comment]
Closed via #186
